version: '3'
services:
  news-mysql:
   image: mysql:5.5
   ports:
     - "3306:3306"
   container_name: mysql-docker-image
   network_mode: host
   environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_DATABASE: newsDb
     MYSQL_USER: app_root
     MYSQL_PASSWORD: root123
  user-app:
    image: user-app
    build: AuthenticateService/
    restart: always
    network_mode: host
    container_name: auth-service-image
    depends_on:
      - news-mysql
    ports:
      - 8089:8089
  news-app:
    image: news-app
    build: Server/
    restart: always
    network_mode: host
    container_name: backend-service-image
    depends_on:
      - news-mysql
    ports:
      - 8081:8081

  angular:
    image: angular-image
    build: UI/
    network_mode: host
    container_name: angular-docker
    ports:
      - 4200:4200